---
framework: jasmine

preMerge:
  pattern:
    - "spec/**/*.js"
postMerge:
  pattern:
    - "spec/**/*.js"
preRun: 
  command: 
    - npm cii
postRun:
  command: 
    - echo 'Done Testing'
version: 1.0

